"""empty message

Revision ID: 161e616afb89
Revises: 
Create Date: 2020-06-29 08:09:57.651234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161e616afb89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Address', sa.Column('location_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Address', 'AddressLocationType', ['location_type_id'], ['id'])
    op.create_foreign_key(None, 'User', 'UserRole', ['user_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_constraint(None, 'Address', type_='foreignkey')
    op.drop_column('Address', 'location_type_id')
    # ### end Alembic commands ###
