"""empty message

Revision ID: 230caf18db73
Revises: 885f25d7c52a
Create Date: 2020-06-04 23:07:52.189189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230caf18db73'
down_revision = '885f25d7c52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRole', sa.Column('can_lookup_other_regions_stats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRole', 'can_lookup_other_regions_stats')
    # ### end Alembic commands ###
