"""empty message

Revision ID: 38faf6cbd2c6
Revises: 81d08da64090
Create Date: 2020-03-27 00:49:37.519661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38faf6cbd2c6'
down_revision = '81d08da64090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TravelType', sa.Column('value', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'TravelType', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TravelType', type_='unique')
    op.drop_column('TravelType', 'value')
    # ### end Alembic commands ###
