"""empty message

Revision ID: 7a9df46c1749
Revises: f36dc55495f9
Create Date: 2020-05-29 18:04:13.214758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9df46c1749'
down_revision = 'f36dc55495f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContactedPersons', sa.Column('is_potential_contact', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContactedPersons', 'is_potential_contact')
    # ### end Alembic commands ###
