"""empty message

Revision ID: 81d08da64090
Revises: 6b6aa97e1b29
Create Date: 2020-03-27 00:23:24.338847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d08da64090'
down_revision = '6b6aa97e1b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('From_Country')
    op.add_column('Patient', sa.Column('travel_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Patient', 'TravelType', ['travel_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Patient', type_='foreignkey')
    op.drop_column('Patient', 'travel_type_id')
    op.create_table('From_Country',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"From_Country_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Infected_Country_Category.id'], name='From_Country_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='From_Country_pkey'),
    sa.UniqueConstraint('name', name='From_Country_name_key')
    )
    # ### end Alembic commands ###
