"""empty message

Revision ID: 83df3f8cb8b5
Revises: 998dcc080553
Create Date: 2020-06-03 17:52:45.617776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83df3f8cb8b5'
down_revision = '998dcc080553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRole', sa.Column('can_see_success_add_window', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRole', 'can_see_success_add_window')
    # ### end Alembic commands ###
