"""empty message

Revision ID: 885f25d7c52a
Revises: bc70b9421488
Create Date: 2020-06-04 13:28:38.990261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885f25d7c52a'
down_revision = 'bc70b9421488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRole', sa.Column('can_add_edit_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRole', 'can_add_edit_user')
    # ### end Alembic commands ###
