"""empty message

Revision ID: 89f36f03b664
Revises: d8176382c665
Create Date: 2020-04-11 16:55:32.304064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f36f03b664'
down_revision = 'd8176382c665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OldDataTravel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('attrs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ContactedPersons', sa.Column('infected_patient_id', sa.Integer(), nullable=True))
    op.drop_constraint('ContactedPersons_infected_person_id_fkey', 'ContactedPersons', type_='foreignkey')
    op.create_foreign_key(None, 'ContactedPersons', 'Patient', ['infected_patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ContactedPersons', 'infected_person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContactedPersons', sa.Column('infected_person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ContactedPersons', type_='foreignkey')
    op.create_foreign_key('ContactedPersons_infected_person_id_fkey', 'ContactedPersons', 'Patient', ['infected_person_id'], ['id'])
    op.drop_column('ContactedPersons', 'infected_patient_id')
    op.drop_table('OldDataTravel')
    # ### end Alembic commands ###
