"""empty message

Revision ID: 998dcc080553
Revises: 7a9df46c1749
Create Date: 2020-06-02 15:31:52.150099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998dcc080553'
down_revision = '7a9df46c1749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('can_add_air', sa.Boolean(), nullable=True),
    sa.Column('can_add_train', sa.Boolean(), nullable=True),
    sa.Column('can_add_auto', sa.Boolean(), nullable=True),
    sa.Column('can_add_foot', sa.Boolean(), nullable=True),
    sa.Column('can_add_sea', sa.Boolean(), nullable=True),
    sa.Column('can_add_local', sa.Boolean(), nullable=True),
    sa.Column('can_add_blockpost', sa.Boolean(), nullable=True),
    sa.Column('can_lookup_own_patients', sa.Boolean(), nullable=True),
    sa.Column('can_lookup_other_patients', sa.Boolean(), nullable=True),
    sa.Column('can_found_by_default', sa.Boolean(), nullable=True),
    sa.Column('can_set_infected', sa.Boolean(), nullable=True),
    sa.Column('can_set_hospital_home_quarant', sa.Boolean(), nullable=True),
    sa.Column('can_set_transit', sa.Boolean(), nullable=True),
    sa.Column('can_access_contacted', sa.Boolean(), nullable=True),
    sa.Column('can_delete_own_patients', sa.Boolean(), nullable=True),
    sa.Column('can_delete_other_patients', sa.Boolean(), nullable=True),
    sa.Column('can_export_patients', sa.Boolean(), nullable=True),
    sa.Column('can_export_contacted', sa.Boolean(), nullable=True),
    sa.Column('can_add_edit_hospital', sa.Boolean(), nullable=True),
    sa.Column('can_block_own_region_accounts', sa.Boolean(), nullable=True),
    sa.Column('can_block_all_accounts', sa.Boolean(), nullable=True),
    sa.Column('can_access_roles', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.add_column('User', sa.Column('user_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'UserRole', ['user_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'user_role_id')
    op.drop_table('UserRole')
    # ### end Alembic commands ###
