"""empty message

Revision ID: bc70b9421488
Revises: 99ebfae92381
Create Date: 2020-06-04 12:55:36.889570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc70b9421488'
down_revision = '99ebfae92381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRole', sa.Column('can_access_various_exports', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRole', 'can_access_various_exports')
    # ### end Alembic commands ###
