"""empty message

Revision ID: e7e960f5cd18
Revises: 230caf18db73
Create Date: 2020-06-04 23:47:34.532848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e960f5cd18'
down_revision = '230caf18db73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRole', sa.Column('can_access_user_info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRole', 'can_access_user_info')
    # ### end Alembic commands ###
