"""empty message

Revision ID: ec5f7d5a9690
Revises: fab9bd53103a
Create Date: 2020-04-28 06:25:17.877016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec5f7d5a9690'
down_revision = 'fab9bd53103a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patient', 'is_infected')
    op.drop_column('Patient', 'is_found')
    op.add_column('PatientState', sa.Column('attrs', sa.JSON(), nullable=True))
    op.add_column('PatientState', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('PatientState', 'detection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('PatientState_patient_id_fkey', 'PatientState', type_='foreignkey')
    op.drop_constraint('PatientState_state_id_fkey', 'PatientState', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('PatientState_state_id_fkey', 'PatientState', 'State', ['state_id'], ['id'])
    op.create_foreign_key('PatientState_patient_id_fkey', 'PatientState', 'Patient', ['patient_id'], ['id'])
    op.alter_column('PatientState', 'detection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('PatientState', 'id')
    op.drop_column('PatientState', 'attrs')
    op.add_column('Patient', sa.Column('is_found', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Patient', sa.Column('is_infected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
